service: lambda-awsSchedular-typescript 

provider:
  profile: serverless-deploy
  name: aws

functions:
  hello:
    handler: handler.hello
    events:
      - eventBridge:
          useCloudFormation: true
          schedule: cron(* * * * ? *)
          input:
            name:MitanshGor
            age:10
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

custom:
  prune:
    automatic: true

package:
  exclude:
    - coverage/**
    - scripts/**
    - serverless.yml
    - .nyc_output/**
    - .idea/**
    - test/**
    - scripts/**
    - package-lock.json
    - .gitlab-ci.yml
    - README.md
    - serverless.yml.example